[project]
name = "xscrape"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11,<4.0"
dependencies = ["twscrape (==0.17.0)", "openai (==1.98.0)", "backoff (==2.2.1)"]
